/* ============================================================================
   The questions on the planes.

   DRAFT COPY — written to be general and careful, not as policy. Have IEX
   review every answer before this goes anywhere public: wording, accuracy,
   and anything CMU does differently.

   Each entry is one sheet: `q` is printed large, `a` underneath. Keep answers
   to about 60 words so they sit comfortably on the ruled lines. There are 50
   here and 100 planes; each question flies on two planes, far apart. Add more
   and the garden uses them — with 100 or more, every plane is different.
   ========================================================================== */
window.GARDEN_QUESTIONS = [
  { q: 'What is IEX?',
    a: 'IEX is Carnegie Mellon’s Office for Institutional Equity and Title IX. It’s a place to ask questions, talk through your options, and get support when something feels unfair, unsafe, or wrong.' },
  { q: 'Can I just ask a question?',
    a: 'Yes. You can ask without starting anything. A question is not a report, and it doesn’t commit you to a next step. The next step is yours.' },
  { q: 'Do I have to give my name?',
    a: 'You can ask general questions without sharing your name. If you later want IEX to take a specific action, they may need more detail — and they’ll tell you what and why before you decide.' },
  { q: 'Will reaching out start an investigation?',
    a: 'Reaching out is not the same as filing a formal complaint. IEX will walk you through your options, and in most situations you decide what happens next.' },
  { q: 'What happens after I send an email?',
    a: 'Someone from IEX writes back to offer a time to talk, if you want to. That first conversation is about your options and the support available — not about deciding anything on the spot.' },
  { q: 'What is a supportive measure?',
    a: 'Practical help while you figure things out — for example, changes to class or work schedules, housing adjustments, extensions, or a no-contact directive. You can ask for support whether or not you file a complaint.' },
  { q: 'What does Title IX cover?',
    a: 'Title IX is a federal law that prohibits sex-based discrimination in education, including sexual harassment and sexual violence. IEX can explain how it applies to your situation.' },
  { q: 'Is there a deadline to reach out?',
    a: 'You can reach out at any time. If you’re thinking about a formal option, asking sooner can help — but it’s never too late to ask a question or to get support.' },
  { q: 'Can I bring someone with me?',
    a: 'In most meetings you can bring a friend or support person. IEX can tell you how that works for the step you’re at.' },
  { q: 'What if it happened off campus?',
    a: 'You can still reach out. Whether a formal process applies can depend on where and how something happened, but support and options are available either way.' },
  { q: 'What if the other person isn’t a student?',
    a: 'You can still reach out — whether they’re a student, staff, faculty, or not part of CMU at all. IEX can explain what’s possible in each case.' },
  { q: 'What if I’m not sure it “counts”?',
    a: 'You don’t have to label what happened before you reach out. Describing it in your own words is enough; IEX can help you make sense of it and of your options.' },
  { q: 'Can I reach out for a friend?',
    a: 'Yes. You can ask how to support someone, or what their options might be, without naming them.' },
  { q: 'How do I help a friend who told me something?',
    a: 'Listen, believe them, and let them lead. You can mention that IEX exists and that they can ask questions without starting anything. You can also reach out yourself for advice on how to help.' },
  { q: 'I work at CMU. What if a student tells me something?',
    a: 'Many CMU employees have responsibilities to share what they learn with IEX. If you’re unsure what yours are, ask IEX — they can explain, and help you support the student.' },
  { q: 'Who will know that I reached out?',
    a: 'IEX treats what you share as private and shares it only with people who need it to respond or provide support. You can ask exactly who would be told before you share any details.' },
  { q: 'What’s the difference between confidential and private?',
    a: 'Confidential resources generally don’t share what you tell them without your permission. Private means information is shared only with the people who need it. IEX can tell you which campus resources are confidential.' },
  { q: 'Can someone retaliate against me for speaking up?',
    a: 'Retaliation — for reaching out, reporting, or taking part in a process — is prohibited. If it happens, tell IEX.' },
  { q: 'Can I change my mind later?',
    a: 'In most situations, yes. You can take a step, pause, or choose a different path later. Reaching out once doesn’t lock you into anything.' },
  { q: 'What is a no-contact directive?',
    a: 'An instruction that two people not communicate with each other, directly or through others. It’s one kind of supportive measure IEX can talk with you about.' },
  { q: 'Do I need proof before I reach out?',
    a: 'No. You don’t need evidence to ask questions or to get support. If you choose a formal process, IEX will explain what information is helpful then.' },
  { q: 'What if it happened a long time ago?',
    a: 'You can still reach out. Support and options don’t simply expire because time has passed.' },
  { q: 'What if I’d been drinking?',
    a: 'You can still reach out. Ask IEX how alcohol or drug use is treated when someone comes forward — the focus is on your safety and your options.' },
  { q: 'Can I get help with my classes?',
    a: 'Academic adjustments — extensions, section changes, or other support — can be arranged as supportive measures. Ask IEX what’s possible for you.' },
  { q: 'Is IEX only about sexual misconduct?',
    a: 'No. IEX’s work covers discrimination and harassment more broadly, not only Title IX. You can ask about anything that feels unfair or unsafe.' },
  { q: 'How do I contact IEX?',
    a: 'Email institutionalequity@cmu.edu or call (412) 268-7125.' },
  { q: 'What do I write in my first email?',
    a: 'Something short is fine: “I have a question and would like to talk.” You don’t need to explain everything in writing.' },
  { q: 'What if I’m in danger right now?',
    a: 'If you’re in immediate danger, call 911. IEX is there for questions, options, and support — not emergencies.' },
  { q: 'Will my family be told?',
    a: 'Ask IEX before you share details. They can explain who would and wouldn’t be informed, and when.' },
  { q: 'Could reaching out affect my grades or my job?',
    a: 'It shouldn’t. Retaliation is prohibited, and IEX can help if you’re worried about how something might affect your classes or your work.' },
  { q: 'What if I don’t want them to get in trouble?',
    a: 'That’s okay to feel. You can still get support and ask about options that don’t involve discipline. IEX will walk through what’s possible.' },
  { q: 'What is an informal resolution?',
    a: 'Some situations can be addressed through an agreed process rather than an investigation. Whether it’s available depends on the situation; IEX can explain.' },
  { q: 'What is a formal complaint?',
    a: 'A request for the university to look into an allegation through a defined process. IEX explains each step before you decide whether that path is right for you.' },
  { q: 'How long does a process take?',
    a: 'It depends on the situation and the path you choose. IEX can give you a sense of timing and keep you updated along the way.' },
  { q: 'Can we meet by phone or video?',
    a: 'You can ask to meet in person, by phone, or by video — whatever feels more comfortable.' },
  { q: 'Is IEX for grad students and staff too?',
    a: 'Yes. You can reach out whether you’re an undergraduate, a graduate student, a postdoc, staff, or faculty.' },
  { q: 'I’m an international student. Can I still ask?',
    a: 'Yes. You can ask questions without starting anything. If you’re worried about how a situation might affect your status, ask IEX who can help with those questions.' },
  { q: 'Can someone else report for me?',
    a: 'Someone can share information with IEX, but you’ll still get to decide how — and whether — you take part.' },
  { q: 'What if it’s my professor or my supervisor?',
    a: 'You can still reach out. Situations with a power difference are exactly the kind IEX can help with, including support with classes or work arrangements.' },
  { q: 'Can I report anonymously?',
    a: 'You can share information without your name. Anonymous reports can limit what IEX is able to do in response, so ask them to explain the trade-offs.' },
  { q: 'What if I’m the one who was accused?',
    a: 'You can reach out too. IEX can explain the process, your rights, and the support that’s available to you.' },
  { q: 'What does “the next step is yours” mean?',
    a: 'That reaching out is a question, not a commitment. You choose whether, when, and how anything happens next — IEX helps you see your options.' },
  { q: 'Can I read about my options first?',
    a: 'Yes. Start by reading, then reach out whenever you’re ready — or not at all.' },
  { q: 'What counts as harassment?',
    a: 'Generally, unwelcome conduct connected to who you are that’s serious enough to get in the way of your work or education. You don’t need to decide whether something meets a definition before you ask.' },
  { q: 'What is stalking?',
    a: 'A pattern of behavior aimed at one person that would make a reasonable person afraid or seriously distressed — repeated contact, following, monitoring. IEX can help with options and safety planning.' },
  { q: 'What about online harassment?',
    a: 'Online and digital harassment can be addressed too — messages, posts, or images shared without consent. Save what you can, and reach out.' },
  { q: 'What if it’s happening where I live?',
    a: 'You can reach out about situations in housing too. Support can include help with living arrangements.' },
  { q: 'Will I have to see the other person?',
    a: 'Not necessarily. There are often ways to limit contact, including during a process. Ask IEX what’s possible for you.' },
  { q: 'It happened before I came to CMU. Can I talk to IEX?',
    a: 'You can talk with IEX about it. Even when a formal process doesn’t apply, they can point you toward support.' },
  { q: 'Is talking to IEX the same as going to the police?',
    a: 'No. IEX is a university office. You can choose to involve the police too, or not — IEX can help you understand both paths.' }
];
